import { expect } from '@playwright/test'
import type { Page } from '@playwright/test'

/**
 * Data every spec owns outright.
 *
 * The suite runs against **one** database — one Worker, one D1, seeded once by
 * `seed.ts`. That is not going to change: a per-file database would mean a
 * Worker per file, and the whole point of these tests is that they exercise the
 * real deployed shape.
 *
 * So isolation here is not "a database each". It is **ownership**: every spec
 * creates the trip it acts on, names it so no other spec can find it by
 * accident, and cleans it up afterwards. Nothing reads `trips[0]`.
 *
 * `trips[0]` is what made this necessary. `/api/trips` returns
 * `ORDER BY start_date DESC`, so it hands back whichever trip some *other* spec
 * happened to create with the latest start date — and three files were then
 * packing rows, unpacking them, and asserting on the reasons of a trip they did
 * not own, while its owner mutated it in parallel. Every symptom in doc 09 §5a
 * follows from that: passes in isolation, fails in a full run, depends on the
 * order the files happen to run in.
 */

export const PASSPHRASE = process.env.E2E_PASSPHRASE ?? 'pack-smart-e2e-passphrase'

/**
 * A name no other spec will match.
 *
 * Three parts, and each earns its place. The **owner** makes a stray match
 * legible in a failure message — "who created `Swipe 4823`?" has an answer. The
 * **counter** separates tests inside one file. The **random suffix** is what
 * makes it safe under parallel workers, where two files can reach the same
 * millisecond; `performance.now()` alone could not promise that, and the old
 * `uniqueName` helpers used exactly that.
 */
let counter = 0
export function ownedName(owner: string): string {
  counter += 1
  const suffix = Math.random().toString(36).slice(2, 8)
  return `${owner} ${counter}-${suffix}`
}

/** The unlock dance, which every spec was copying. */
export async function signIn(page: Page): Promise<void> {
  await page.goto('/')
  await page.getByLabel('Passphrase').fill(PASSPHRASE)
  await page.getByRole('button', { name: 'Unlock' }).click()
  await expect(page.getByRole('navigation', { name: 'Primary' })).toBeVisible()
}

export interface TripFixture {
  id: string
  name: string
}

export interface TripOptions {
  /** Who is creating it — a short spec-file name, for legible failures. */
  owner: string
  startDate?: string
  endDate?: string
  destination?: string
  country?: string
  activities?: string[]
  international?: boolean
  laundryAvailable?: boolean
  flightHours?: number
}

/**
 * Creates a trip through the real API and returns it.
 *
 * Through the API rather than the trip sheet, deliberately. Clicking through
 * the sheet takes a dozen round trips and is the slowest thing in the suite;
 * more importantly it makes every test that merely *needs* a trip also a test
 * OF the trip sheet, so a change to that sheet breaks twenty unrelated files.
 * The specs that are genuinely about creating a trip still use the sheet.
 *
 * The checklist is generated by the endpoint itself, so the trip comes back
 * ready to act on.
 */
export async function createTrip(page: Page, options: TripOptions): Promise<TripFixture> {
  const name = ownedName(options.owner)

  const trip = await page.evaluate(
    async ([payload]) => {
      const response = await fetch('/api/trips', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: payload as string,
      })
      if (!response.ok) {
        throw new Error(`createTrip: ${response.status} ${await response.text()}`)
      }
      const body = (await response.json()) as { trip: { id: string; name: string } }
      return body.trip
    },
    [
      JSON.stringify({
        name,
        startDate: options.startDate ?? '2026-07-31',
        endDate: options.endDate ?? '2026-08-11',
        destinations: [
          { name: options.destination ?? 'Cape Town', country: options.country ?? 'South Africa' },
        ],
        activities: options.activities ?? ['safari', 'nice_dinner'],
        international: options.international ?? true,
        laundryAvailable: options.laundryAvailable ?? false,
        flightHours: options.flightHours ?? 15,
      }),
    ],
  )

  return { id: trip.id, name }
}

/**
 * Gets rid of a trip the spec created.
 *
 * Best effort on purpose: a teardown that throws turns one failed assertion
 * into a failed assertion *and* a confusing second error, and the trip's name
 * is unique so leaving one behind cannot break another spec. What it does buy
 * is a database that does not grow by twenty trips per run, which is its own
 * slow kind of interference.
 */
export async function deleteTrip(page: Page, id: string): Promise<void> {
  await page
    .evaluate(
      async ([tripId]) => {
        await fetch(`/api/trips/${tripId}`, { method: 'DELETE' })
      },
      [id],
    )
    .catch(() => {})
}

/**
 * An item this spec owns, for the tests that mutate GLOBAL catalog state.
 *
 * The amounts and rules screens write `packing_rule` rows, which are not scoped
 * to a trip — a per-day amount on a garment changes the quantity on *every*
 * trip's list, including the ones other specs are asserting on. Doing that to a
 * shared item is the second interference class in doc 09 §5a, and the reason a
 * failed run could poison a local database permanently: the amount picker hides
 * items that already have an amount, so a test that died before its cleanup
 * could never find its item again.
 *
 * A fresh item per test removes both halves. Nothing else asserts on it, and a
 * leftover one is invisible rather than fatal.
 */
export async function createOwnedItem(
  page: Page,
  owner: string,
  overrides: Record<string, unknown> = {},
): Promise<{ id: string; name: string }> {
  const name = ownedName(owner)

  const id = await page.evaluate(
    async ([payload]) => {
      const response = await fetch('/api/items', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: payload as string,
      })
      if (!response.ok) {
        throw new Error(`createOwnedItem: ${response.status} ${await response.text()}`)
      }
      // `POST /api/items` answers with the item itself, not a wrapper.
      const body = (await response.json()) as { id: string }
      return body.id
    },
    [JSON.stringify({ kind: 'gear', displayName: name, category: 'Travel Gear', ...overrides })],
  )

  return { id, name }
}

/**
 * Removes every usual-amount rule belonging to an item, whatever state the test
 * left it in.
 *
 * A teardown rather than a final step in the test body, and that distinction is
 * the whole point. `packing_rule` is not scoped to a trip, so an amount left
 * behind changes the quantity on every future list — and the amount picker
 * hides items that already have one, so a test that died before its cleanup
 * could never find its item again. That was not a flake: it was permanent until
 * `.wrangler/state` was deleted (doc 09 §5a).
 *
 * Runs on the failure path too, which is the only path where it mattered.
 */
export async function clearAmounts(page: Page, itemId: string): Promise<void> {
  await page
    .evaluate(
      async ([id]) => {
        const listed = await fetch('/api/settings/amounts')
        if (!listed.ok) return
        const { amounts } = (await listed.json()) as {
          amounts: Array<{ ruleId: string; itemId: string }>
        }
        for (const amount of amounts.filter((a) => a.itemId === id)) {
          await fetch(`/api/settings/amounts/${amount.ruleId}`, { method: 'DELETE' })
        }
      },
      [itemId],
    )
    .catch(() => {})
}
